# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c42260f232f39d098e43ac051a72dc07"
name = "BoDIntegration"
handle = "bodintegration"
application_url = "https://bodintegration-411044834097.herokuapp.com/"
embedded = true
store = "795047-3.myshopify.com"

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

[auth]
redirect_urls = [
  "https://bodintegration-411044834097.herokuapp.com/api/auth/callback",
  "https://bodintegration-411044834097.herokuapp.com/shopify/callback"
]

[pos]
embedded = false
