# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b06825b345221d875ba8870673cfc80d"
application_url = "https://example.com/"
embedded = true
name = "bod-dropshipping"
handle = "bod-dropshipping"

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/api/webhooks/app_scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/api/webhooks/app_uninstalled"

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/customers_data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/customers_redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/shop_redact"
  compliance_topics = [ "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[pos]
embedded = false
